server:
  port: 8080

spring:
  profiles:
    active: crud
  mvc:
    view:
      prefix: WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/capstone_project
    username: postgres
    password: 1111

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect